agg_funcs = {'assists': 'sum',
             'boosts': 'sum',
             'damageDealt': 'sum',
             'DBNOs': 'sum',
             'headshotKills': 'sum',
             'heals': 'sum',
             'killPlace': 'min',
             'killPoints': 'sum',
             'kills': 'sum',
             'killStreaks': 'sum',
             'longestKill': 'max',
             'matchDuration': 'mean',
             'matchType': 'max',
             'maxPlace': 'max',  # may not equal to group num
             'numGroups': 'max',
             'rankPoints': 'sum',  # depatured in next version
             'revives': 'sum',
             'rideDistance': 'sum',
             'roadKills': 'sum',
             'swimDistance': 'sum',
             'teamKills': 'sum',
             'vehicleDestroys': 'sum',
             'walkDistance': 'sum',
             'weaponsAcquired': 'sum',
             'winPoints': 'sum',  # rankPoints where only win counts
             'winPlacePerc': 'max'}
